config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'accounts#index'
        resources :accounts, only: [:index, :new,:create] do
            member do
                  #get '/portfolios', to: 'portofolios#index'
                  
            resources :portfolios, only: [:new,:create] do
                member do
                      get '/', to: 'portfolios#index'
                end
        end
            end
        end
        
end

app/models/account.rb
class Account < ApplicationRecord
    
    has_many :portfolios, dependent: :delete_all
    
   
    
    def deposit(amount)
        self.update!(balance: self.balance+amount)
    end
    
    def find_portfolios
        @portfolios = self.portfolios
        @portfolios
    end
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    
    has_many    :stocks, dependent: :delete_all
    
    def find_stocks(name)
        @name = name
        self.stocks.where(name: @name)
        
    end
    
    def stocks()
        self.stocks
    end
end

app/models/stock.rb
class Stock < ApplicationRecord
end

app/controllers/accounts_controller.rb
class AccountsController <ApplicationController
    
    def index
        @accounts = Account.order(id: :asc)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    
    def index
        @portfolios = Portfolio.order(id: :asc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/index.html.erb
<h2 class="display-4">Account List</h2>

<table class="table table-striped">
    
    <thead class="thead-inverse">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>balance</th>
            <th>Portfolio</th>
        </tr>
    </thead>
    <tbody>
            <% @accounts.each do |a| %>
            <tr>
                <td>
                    <%= a.id %>
                </td>
                
                <td><%= a.name%></td>
                
                <td><%= a.balance %></td>
              
                <td><div class="list-group">
              
                <% a.find_portfolios .each do |p|%>
                        <%= link_to p.name, portfolio_path(a,p), class: "btn btn-secondary btn-sm btn-block" %>
                <% end %>
                </div>
                </td>
                
            </tr>
            <% end %>
      
    </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trade</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/portfolios/index.html.erb
<h2 class="display-4">Account List</h2>

<table class="table table-striped">
    
    <thead class="thead-inverse">
        <tr>
            <th>Id</th>
            <th>Name</th>
           
        </tr>
    </thead>
    <tbody>
            <% @portfolios.each do |p| %>
            <tr>
                <td>
                    <%= p.id %>
                </td>
                
                <td><%= p.name%></td>
                
                
            </tr>
            <% end %>
      
    </tbody>
</table>